// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: openliberty-operator-openshift
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2022-03-25
:page-description: Explore how to deploy a microservice to Red Hat OpenShift 4 by using the Open Liberty Operator.
:page-tags: ['Kubernetes', 'Docker', 'Cloud'] 
:page-permalink: /guides/{projectid}
:page-related-guides: ['cloud-openshift', 'cloud-openshift-operator', 'okd']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:imagesdir: /img/guide/{projectid}
:source-highlighter: prettify
:page-seo-title: Deploying a microservice to Red Hat OpenShift 4 by using Open Liberty Operator
:page-seo-description: A getting started tutorial with examples on how to deploy a cloud-native Java application and a microservice to Red Hat OpenShift 4 cluster by using a Kubernetes Operator like the Open Liberty Operator.
:guide-author: Open Liberty
= Deploying a microservice to OpenShift 4 by using Open Liberty Operator

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Explore how to deploy a microservice to Red Hat OpenShift 4 by using Open Liberty Operator.

== What you'll learn

You will learn how to deploy a cloud-native application with a microservice to Red Hat OpenShift 4 by using the Open Liberty Operator. 

https://www.openshift.com/[OpenShift^] is a Kubernetes-based platform with added functions. It streamlines the DevOps process by providing an intuitive development pipeline. It also provides integration with multiple tools to make the deployment and management of cloud applications easier. You can learn more about Kubernetes by checking out the https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes^] guide.

https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#operators-in-kubernetes[Kubernetes operators^] provide an easy way to automate the management and updating of applications by abstracting away some of the details of cloud application management. To learn more about operators, check out this https://www.openshift.com/learn/topics/operators[Operators tech topic article^]. 

The application in this guide consists of one microservice, `system`. The system microservice returns the JVM system properties of its host.

You will deploy the `system` microservice by using the Open Liberty Operator. The https://github.com/OpenLiberty/open-liberty-operator[Open Liberty Operator^] provides a method of packaging, deploying, and managing Open Liberty applications on Kubernetes-based clusters. The Open Liberty Operator watches Open Liberty resources and creates various Kubernetes resources, including `Deployments`, `Services`, and `Routes`, depending on the configurations. The Operator then continuously compares the current state of the resources, the desired state of application deployment, and reconciles them when necessary.


// Static guide instruction
ifndef::cloud-hosted[]
== Additional prerequisites

Before you can deploy your microservice, you must gain access to a cluster on OpenShift and have an OpenShift client installed. For client installation instructions, refer to https://docs.openshift.com/container-platform/4.5/cli_reference/openshift_cli/getting-started-cli.html[the official OpenShift Online documentation^].

There are various OpenShift offerings. You can gain access to an OpenShift cluster that is hosted on https://www.openshift.com/products/openshift-ibm-cloud[IBM Cloud^], or check out other offerings https://www.openshift.com/products[from OpenShift^]. 

After you get access to a cluster, make sure you are logged in to the cluster as a cluster administrator by running the following command:

[role='command']
```
oc version
```

Look for output similar to the following example:

[role='no_copy']
```
Client Version: 4.3.13
Server Version: 4.3.13
Kubernetes Version: v1.16.2
```

Before you install any resources, you need to create a project on your OpenShift cluster. Create a project named `guide` by running the following command:

[role='command']
```
oc new-project guide
```

Ensure that you are working within the project `guide` by running the following command:

[role='command']
```
oc projects
```

Look for an asterisk (*) with the `guide` project in the list of projects to confirm that you are in the `guide` project, as shown in the following example:

[role='no_copy']
```
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
  * guide
```
endif::[]

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.

== Installing the Operator

// Static guide instruction
ifndef::cloud-hosted[]
When you obtained your OpenShift cluster, you received login information for the https://docs.openshift.com/container-platform/4.5/web_console/web-console.html[OpenShift web console^]. The web console provides an interface to interact with your OpenShift cluster through your web browser.

To install the Operator, navigate to the web console and select *Operators > OperatorHub* from the sidebar menu. Search for and install the *Open Liberty Operator*.

Make sure you install the Operator into the `guide` namespace. 
endif::[]

// Cloud hosted guide instruction
ifdef::cloud-hosted[]
A project is created for you to use in this exercise. Run the following command to see your project name:

```bash
oc projects
```

In this Skill Network enviornment, the Open Liberty Operator is already installed by the administrator. If you like to learn how to install the Open Liberty Operator, you can learn from the [Deploying microservices to OpenShift by using Kubernetes Operators](https://openliberty.io/guides/cloud-openshift-operator.html#installing-the-operators) guide or the Open Liberty Operator [document](https://github.com/OpenLiberty/open-liberty-operator/blob/master/deploy/releases/0.7.1/readme.adoc).
endif::[]

Run the following command to view all the supported API resources that are available through the Open Liberty Operator:

[role='command']
```
oc api-resources --api-group=apps.openliberty.io
```

Look for the following output, which shows the https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[custom resource definitions^] (CRDs) that can be used by the Open Liberty Operator:

[role='no_copy']
```
NAME                     SHORTNAMES        APIGROUP                     NAMESPACED  KIND
openlibertyapplications  olapp,olapps      apps.openliberty.io/v1beta2  true        OpenLibertyApplication
openlibertydumps         oldump,oldumps    apps.openliberty.io/v1beta2  true        OpenLibertyDump
openlibertytraces        oltrace,oltraces  apps.openliberty.io/v1beta2  true        OpenLibertyTrace
```

Each CRD defines a kind of object that can be used, which is specified in the previous example by the `KIND` value. The `SHORTNAME` value specifies alternative names that you can substitute in the configuration to refer to an object kind. For example, you can refer to the `OpenLibertyApplication` object kind by one of its specified shortnames, such as `olapps`. 

The `openlibertyapplications` CRD defines a set of configurations for deploying an Open Liberty-based application, including the application image, number of instances, and storage settings. The Open Liberty Operator watches for changes to instances of the `OpenLibertyApplication` object kind and creates Kubernetes resources that are based on the configuration that is defined in the CRD.

// Static guide instruction
ifndef::cloud-hosted[]
You can also confirm the installation of the operator from the web console. Navigate to the OperatorHub. From the categories on the left, you can filter to see only installed operators. 

== Adding a private Docker credential

Docker limits container image pull requests for free DockerHub subscriptions. For more information, see link:https://www.docker.com/increase-rate-limits[Understanding Docker Hub Rate Limiting]. If you have a Docker account with a Pro or Team subscription, you can add a private credential to avoid any errors as a result of the limits.

To add a private credential, navigate to the OpenShift web console and select *Workloads > Secrets* from the sidebar menu. Ensure that the selected project is `openshift-config`. Search for `pull-secret` and click the *three vertical dots* menu; then *Edit Secret*. Scroll down and click *Add credentials*. Enter `docker.io` to the *Registry Server Address* field, your Docker user ID to the *Username* field, and your Docker password to the *Password* field. Click the *Save* button to save the credential. 
endif::[]

== Deploying the system microservice to OpenShift

To deploy the `system` microservice, you must first package the microservice, then create and run an OpenShift build to produce runnable container images of the packaged microservice.

=== Packaging the microservice

Ensure that you are in the `start` directory and run the following command to package the `system` microservice:

// Static guide instruction
ifndef::cloud-hosted[]
[role='command']
```
mvn clean package
```
endif::[]

// Cloud hosted guide instruction
ifdef::cloud-hosted[]
```bash
cd /home/project/draft-guide-openliberty-operator-openshift/start
mvn clean package
```
endif::[]

=== Building and pushing the image

Create a build template to configure how to build your container image.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `build.yaml` template file in the `start` directory.#
`build.yaml`
----

//File 0
build.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/build.yaml[]
----

The [hotspot file=0]`build.yaml` template includes two objects. The [hotspot=imageStream file=0]`ImageStream` object provides an abstraction from the image in the image registry. This allows you to reference and tag the image. The image registry used is the integrated internal OpenShift Container Registry.

The [hotspot=buildConfig file=0]`BuildConfig` object defines a single build definition and any triggers that kickstart the build. The [hotspot=source file=0]`source` spec defines the build input. In this case, the build inputs are your [hotspot=binary file=0]`binary` (local) files, which are streamed to OpenShift for the build. The uploaded files need to include the packaged `WAR` application binaries, which is why you needed to run the Maven commands. The template specifies a [hotspot=docker file=0]`Docker` strategy build, which invokes the `docker build` command, and creates a runnable container image of the microservice from the build input.

Run the following command to create the objects for the `system` microservice:

[role='command']
```
oc process -f build.yaml | oc create -f -
```

Next, run the following command to view the newly created `ImageStream` objects and the build configurations for the microservice:

[role='command']
```
oc get all -l name=system
```

Look for the following similar resources:

[role='no_copy']
```
NAME                                                TYPE     FROM     LATEST
buildconfig.build.openshift.io/system-buildconfig   Docker   Binary   0

NAME                                                IMAGE REPOSITORY                                                                   TAGS           UPDATED
imagestream.image.openshift.io/system-imagestream   default-route-openshift-image-registry.apps-crc.testing/guide/system-imagestream
```   

Ensure that you are in the `start` directory and trigger the build by running the following command:

[role='command']
```
oc start-build system-buildconfig --from-dir=system/.
```

The local `system` directory is uploaded to OpenShift to be built into the Docker image. Run the following command to list the build and track its status:

[role='command']
```
oc get builds
```

Look for the output that is similar to the following example:

[role='no_copy']
```
NAME                    TYPE     FROM             STATUS     STARTED
system-buildconfig-1    Docker   Binary@f24cb58   Running    45 seconds ago
```

You may need to wait some time until the build is complete. To check whether the build is complete, run the following command to view the build log until the `Push successful` message appears:

[role='command']
```
oc logs build/system-buildconfig-1
```

=== Checking the image

During the build process, the image associated with the `ImageStream` object that you created earlier was pushed to the image registry and tagged. Run the following command to view the newly updated `ImageStream` object:

[role='command']
```
oc get imagestreams
```

Run the following command to get more details on the newly pushed image within the stream:

[role='command']
```
oc describe imagestream/system-imagestream
```

The following example shows part of the `system-imagestream` output:

[role='no_copy']
```
Name:               system-imagestream
Namespace:          guide
Created:            2 minutes ago
Labels:             name=system
Annotations:        <none>
Image Repository:   default-route-openshift-image-registry.apps-crc.testing/guide/system-imagestream
Image Lookup:       local=false
Unique Images:      1
Tags:               1

...
```

Now you're ready to deploy the image.

=== Deploying the image

You can configure the specifics of the Open Liberty Operator-controlled deployment with a YAML configuration file.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `deploy.yaml` configuration file in the `start` directory.#
`deploy.yaml`
----

deploy.yaml
[source, yaml, linenums, role='code_column hide_tags=healthProbes']
----
include::finish/deploy.yaml[]
----

The [hotspot file=0]`deploy.yaml` file is configured to deploy one [hotspot=olapp file=0]`OpenLibertyApplication` resource, [hotspot=system file=0]`system`, which is controlled by the Open Liberty Operator.

The [hotspot=sysImage file=0]`applicationImage` parameter defines what container image is deployed as part of the `OpenLibertyApplication` CRD. This parameter follows the `<project-name>/<image-stream-name>[:tag]` format. The parameter can also point to an image hosted on an external registry, such as Docker Hub. The [hotspot=system file=0]`system` microservice is configured to use the [hotspot=sysImage file=0]`image` created from the earlier build. 

One of the benefits of using `ImageStream` objects is that the operator redeploys the application when it detects a new image is pushed. The [hotspot=systemEnv file=0]`env` parameter is used to specify environment variables that are passed to the container at runtime.

Additionally, the microservice includes the [hotspot=service file=0]`service` and [hotspot=expose file=0]`expose` parameters. The [hotspot=servicePort file=0]`service.port` parameter specifies which port is exposed by the container, allowing the microservice to be accessed from outside the container. To access the microservice from outside of the cluster, it must be exposed by setting the [hotspot=expose file=0]`expose` parameter to `true`. After you expose the microservice, the Operator automatically creates and configures routes for external access to your microservice.

// Static guide instruction
ifndef::cloud-hosted[]
Run the following command to deploy the `system` microservice with the previously explained configuration:

[role='command']
```
oc apply -f deploy.yaml
```
endif::[]

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
Run the following commands to update the **applicationImage** and deploy the **system** microservice with the previously explained configuration:
```bash
sed -i 's=guide='"$SN_ICR_NAMESPACE"'=g' deploy.yaml
oc apply -f deploy.yaml
```
endif::[]

Next, run the following command to view your newly created `OpenLibertyApplications` resources:

[role='command']
```
oc get OpenLibertyApplications
```

You can also replace `OpenLibertyApplications` with the shortname `olapps`.

Look for output that is similar to the following example:

[role='no_copy']
```
NAME      IMAGE                                    EXPOSED   RECONCILED   AGE
system    guide/system-imagestream:1.0-SNAPSHOT    true      True         10s
```

A `RECONCILED` state value of `True` indicates that the operator was able to successfully process the `OpenLibertyApplications` instances. Run the following command to view details of your microservice:

[role='command']
```
oc describe olapps/system
```

This example shows part of the `olapps/system` output:

[role='no_copy']
```
Name:         system
Namespace:    guide
Labels:       app.kubernetes.io/part-of=system
              name=system
Annotations:  <none>
API Version:  apps.openliberty.io/v1beta2
Kind:         OpenLibertyApplication

...
```

== Accessing the microservice

To access the exposed `system` microservice, run the following command and make note of the `HOST`:

[role='command']
```
oc get routes
```

Look for an output that is similar to the following example:

[role='no_copy']
```
NAME     HOST/PORT                                                     PATH   SERVICES   PORT       TERMINATION   WILDCARD
system   system-guide.2886795274-80-kota02.environments.katacoda.com          system     9080-tcp                 None
```


Visit the microservice by going to the following URL: 
`http://[HOST]/system/properties`

Make sure to substitute the appropriate `[HOST]` value. For example, using the output from the command above, `system-guide.2886795274-80-kota02.environments.katacoda.com` is the `HOST`. The following example shows this value substituted for `HOST` in the URL: `\http://system-guide.2886795274-80-kota02.environments.katacoda.com/system/properties`.

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
Or, you can run the following command to get the URL:
```bash
IFS=' ' read -r -a system_url <<< "`oc get routes | grep system`"
echo http://${system_url[1]}/system/properties
```

Then, hold the **CTRL** key and click on the URL in the terminal to visit the microservice.
endif::[]

When you’re done trying out the microservice, run following command to stop the microservice:
[role='command']
```
oc delete -f deploy.yaml
```

== Specifying other parameters

You can visit the https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1beta2.adoc#configuration[Open Liberty Operator user guide^] to find all of the supported optional parameters.

You can now configure the startup, readiness, and liveness probes. The [hotspot=startupProbe file=0]`startup probe` is used to verify whether deployed application is fully initialized before the liveness probe takes over, the [hotspot=livenessProbe file=0]`liveness probe` is used to determine whether the application is running, and the [hotspot=readinessProbe file=0]`readiness probe` is used to know whether the application is ready to process requests.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `deploy.yaml` configuration file.#
`deploy.yaml`
----

deploy.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/deploy.yaml[]
----

The health check endpoints `/health/started`, `/health/live` and `/health/ready` have already been created for you. 

// Static guide instruction
ifndef::cloud-hosted[]
Run the following command to deploy the `system` microservice with the new configuration:

[role='command']
```
oc apply -f deploy.yaml
```
endif::[]

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
Run the following commands to update the **applicationImage** and deploy the **system** microservice with the new configuration:
```bash
sed -i 's=system:1.0-SNAPSHOT=us.icr.io/'"$SN_ICR_NAMESPACE"'/system:1.0-SNAPSHOT\n  pullPolicy: Always=g' deploy.yaml
oc apply -f deploy.yaml
```
endif::[]

You can revisit the microservice at `http://[HOST]/system/properties` as the previous section.

== Tearing down the environment

// Static guide instruction
ifndef::cloud-hosted[]
When you no longer need your project, switch to another project and delete the project `guide` by running the following command:

[role='command']
```
oc delete project guide
```

This command deletes all the applications and resources.
endif::[]

// Cloud-hosted guide instruction
ifdef::cloud-hosted[]
When you no longer need your deployed microservice, you can delete all resources by running the following commands:

```bash
oc delete -f deploy.yaml
oc delete imagestream.image.openshift.io/system-imagestream
oc delete bc system-buildconfig
```
endif::[]

== Great work! You're done!

You just deployed a microservice running in Open Liberty to OpenShift 4 by using the Open Liberty Operator.

== Related Links

include::{common-includes}/attribution.adoc[subs="attributes"]
