# tag::system[]
apiVersion: openliberty.io/v1beta1
# tag::olapp[]
kind: OpenLibertyApplication
# end::olapp[]
metadata:
  name: system
  labels:
    name: system
spec:
  # tag::sysImage[]
  applicationImage: guide/system-imagestream:1.0-SNAPSHOT
  # end::sysImage[]
  service:
    # tag::servicePort[]
    port: 9080
    # end::servicePort[]
  # end::service[]
  # tag::expose[]
  expose: true
  # end::expose[]
  # tag::systemEnv[]
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
  # end::systemEnv[]
# end::system[]